version: '3.8'

networks:
  net:
    driver: bridge

volumes:
  docker-storage:

services:
  # This is a controller as DinD
  controller:
    build:
      context: ./Dockerfiles/Dood
      dockerfile: ubuntu-20.04.Dockerfile
    image: dindocker_${DOCKERFILE}_${DIND_SERVICES}_dood
    restart: always
    volumes:
      - './src:/src'
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    privileged: true
    tty: true
    networks:
      - net    

  # DinD Container Configuration
  agent:
    build:
      context: ./Dockerfiles/Dind/${DIND_SERVICES}
      dockerfile: ${DOCKERFILE}.Dockerfile
    image: dindocker_${DOCKERFILE}_${DIND_SERVICES}
    restart: always
    volumes:
      - './src:/src'
      - 'docker-storage/var/lib/docker/image'  # Persist docker images data inside a docker volume to persist over all agents
    privileged: true    
    tty: true
    networks:
      - net          
