version: '3.8'

networks:
  net:
    driver: bridge

volumes:
  docker-storage:
  controller-docker:

services:
  # This is a controller as DinD
  controller:
    build:
      context: .
      dockerfile: ./Dockerfiles/Dind/${DIND_SERVICES}/${DOCKERFILE}.Dockerfile
    image: dindocker_${DOCKERFILE}_${DIND_SERVICES}
    restart: always
    volumes:
      - './src:/src'
      - 'controller-docker:/var/lib/docker'
    ports:
      - "39000:9000"
      - "30080-30090:80-90" # Specify port mapping range to map on the later from dind      
    #  - "80-90" # for dynamic port mapping
    privileged: true
    tty: true
    networks:
      - net    

  # DinD Container Configuration
  agent:
    build:
      context: .
      dockerfile: ./Dockerfiles/Dind/${DIND_SERVICES}/${DOCKERFILE}.Dockerfile
    image: dindocker_${DOCKERFILE}_${DIND_SERVICES}
    restart: always
    volumes:
      - './src:/src'
      - 'docker-storage:/var/lib/docker/image'  # Persist docker images data inside a docker volume to persist over all agents
    privileged: true    
    tty: true
    networks:
      - net          