version: '3.8'

networks:
  net:
    driver: bridge
volumes:
  controller-images:
  controller-docker:
services:
  controller:
    build:
      context: ./Dockerfiles/Dind/Kubernetes
      dockerfile: ${DIND_DOCKERFILE_NAME}
    image: dindocker_k8s_cluster_agent
    restart: always
    volumes:
      - './src:/src'   
      #- 'controller-images:/var/lib/docker/image'
      - 'controller-docker:/var/lib/docker'
    privileged: true    
    ports:
      - "30080-30090:80-90" # Specify port mapping range to map on the later from dind
    working_dir: /src
    tty: true
    networks:
      - net    


  # DinD Container Configuration
  agent:
    build:
      context: ./Dockerfiles/Dind
      dockerfile: ${DIND_DOCKERFILE_NAME}
    image: dindocker_cluster_agent
    restart: always
    volumes:
      - './src:/src'
    ports:
      - "80-90"
    privileged: true    
    tty: true
    networks:
      - net     