apiVersion: v1
kind: Service
metadata:
  name: fleetman-app

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: app

  ports:
    - name: http
      port: 80
      nodePort: 30080

  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: nginx1.14.2 # Label Selector
  ports:
    - name: http
      port: 80
      nodePort: 30080
  type: NodePort


# You can start this file with apply -f /src/kubernetes/Services/nginx-replicaset.yaml