
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  # minReadySeconds: 30
  selector:
    matchLabels:
      app: app
  replicas: 2
  template: # template for the pods
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: image:release0-5

---
apiVersion: v1
kind: Pod
metadata:
  name: queue
  labels:
    app: queue
spec:
  containers:
  - name: queue
    image: richardchesterwood/k8s-fleetman-queue:release1
